[package]
name = "rush-png"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.0.2", features = ["derive"] }
crc = "3.0.0"
structopt = "0.3"